document.write("<html lang=\"en\">");
document.write("    <head>");
document.write("        <meta charset=\"UTF-8\">");
document.write("        <title>iTowns+<\/title>");
document.write("        <link rel=\"stylesheet\" href=\"css\/main.css\">");
document.write("    <\/head>");
document.write("    <body onload = \"loadAdaptiveInterface(false)\">");
document.write("        ");
document.write("    ");
document.write("        <script type=\"text\/javascript\">");
document.write("");
document.write("            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){");
document.write("            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),");
document.write("            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)");
document.write("            })(window,document,'script','\/\/www.google-analytics.com\/analytics.js','ga');");
document.write("");
document.write("            ga('create', 'UA-47993651-1', 'itowns.fr');");
document.write("            ga('send', 'pageview');");
document.write("");
document.write("");
document.write("");
document.write("            \/\/ Function that analyzes the parameters in order to launch the good app");
document.write("            function loadAdaptiveInterface(flag) {");
document.write("");
document.write("                var params= {};");
document.write("");
document.write("                var tmp= window.location.search.substr(1).split(\"&\");  \/\/ Adresse ex: http:\/\/www.itowns.fr\/viewer\/laserADVIewer.html?date=2008_05_05&hour=14&seconds=350&easting=655550.2&northing=6866565.3");
document.write("                for (i=0; i<tmp.length; i++)");
document.write("                {");
document.write("                    data=tmp[i].split(\"=\");");
document.write("                    params[data[0].toLowerCase()]=data[1];");
document.write("                }");
document.write("");
document.write("                switch(params.app){");
document.write("");
document.write("                    case \"iforest\": document.getElementById(\"biomasse\").style.display = \"block\";");
document.write("                                    logoApp.src = \"images\/logo_iforest_27x95.png\";");
document.write("                                    break;");
document.write("");
document.write("                    case \"geovelo\": break;");
document.write("                    case \"terramob\": break;");
document.write("                    default:        break;");
document.write("");
document.write("");
document.write("                }");
document.write("            }");
document.write("        <\/script>");
document.write("");
document.write("        <div class=\"control control--text recherche\" id=\"search\">");
document.write("            <label for=\"text1\" id=\"recherche1\">Recherche<\/label>");
document.write("            <input class=\"control-text\" id=\"text1\" type=\"text\" placeholder=\"Adresse, Ville, ...\">");
document.write("            <input class=\"control-button\" id=\"recherche2\" type=\"submit\" value=\"Aller à\">");
document.write("        <\/div>");
document.write("        <div class=\"sidebar\" id=\"sidebar\">");
document.write("            <h1 class=\"logo\"><img src=\"images\/itowns.png\" data-img=\"images\/itowns-small.png\" alt=\"towns+ - Site officiel\" id=\"logoApp\"><\/h1>");
document.write("            <div class=\"panel panel--expandable panel--expanded\">");
document.write("                <h2 class=\"panel-titlePrimary icon icon--map\">Plan<\/h2>");
document.write("                <div class=\"panel-inner\">");
document.write("                    <div class=\"panel-content panel-content--minimap\">");
document.write("                        <div id=\"geoportailDiv\" style=\"height:300px\"><\/div>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("            <\/div>");
document.write("            <div class=\"panel panel--expandable\">");
document.write("                <h2 class=\"panel-titlePrimary icon icon--layers\">Couches<\/h2>");
document.write("                <div class=\"panel-inner\">");
document.write("                    <div class=\"panel-content\">");
document.write("                        <h3 class=\"panel-titleSecondary\">Laser<\/h3>");
document.write("                        <div class=\"control control--checkbox\">");
document.write("                            <input class=\"control-checkbox\" type=\"checkbox\" id=\"checkbox1\">");
document.write("                            <label for=\"checkbox1\">Afficher laser<\/label>");
document.write("                        <\/div>");
document.write("                        <div class=\"control control--range\">");
document.write("                            <label class=\"panel-titleSecondary\">Taille<\/label>");
document.write("                            <div class=\"control-range\" data-min=\"0\" data-max=\"100\" data-value=\"10\" id=\"range1\"><\/div>");
document.write("                        <\/div>");
document.write("                        <div class=\"control control--range\">");
document.write("                            <label class=\"panel-titleSecondary\">Transparence<\/label>");
document.write("                            <div class=\"control-range\" data-min=\"0\" data-max=\"100\" data-value=\"70\" id=\"range2\"><\/div>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("                    <div class=\"panel-content\">");
document.write("                        <h3 class=\"panel-titleSecondary\">Panoramique<\/h3>");
document.write("                        <div class=\"control control--checkbox\">");
document.write("                            <input class=\"control-checkbox\" type=\"checkbox\" checked id=\"checkbox2\">");
document.write("                            <label for=\"checkbox2\">Afficher panoramique<\/label>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("");
document.write("                    <div class=\"panel-content\">");
document.write("                        <h3 class=\"panel-titleSecondary\">Cartography 3D<\/h3>");
document.write("                        <div class=\"control control--checkbox\">");
document.write("                            <input class=\"control-checkbox\" type=\"checkbox\" id=\"chbxCarto3D\">");
document.write("                            <label for=\"chbxCarto3D\">Afficher Bati 3D<\/label>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("");
document.write("                     <div class=\"panel-content\">");
document.write("                        <h3 class=\"panel-titleSecondary\">Orthophoto<\/h3>");
document.write("                        <div class=\"control control--checkbox\">");
document.write("                            <input class=\"control-checkbox\" type=\"checkbox\" checked id=\"checkbox3\">");
document.write("                            <label for=\"checkbox3\">Afficher Orthophoto<\/label>");
document.write("                        <\/div>");
document.write("                        <div class=\"control control--range\">");
document.write("                                <label class=\"panel-titleSecondary\">Transparence<\/label>");
document.write("                                <div class=\"control-range\" data-min=\"0\" data-max=\"100\" data-value=\"100\" id=\"range3\"><\/div>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("");
document.write("");
document.write("                    <div class=\"panel-content\">");
document.write("                        <h3 class=\"panel-titleSecondary\">MNT<\/h3>");
document.write("                        <div class=\"control control--checkbox\">");
document.write("                            <input class=\"control-checkbox\" type=\"checkbox\" id=\"checkbox4\">");
document.write("                            <label for=\"checkbox4\">Afficher MNT<\/label>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("                    <div class=\"panel-content\">");
document.write("                        <h3 class=\"panel-titleSecondary\">Geonames<\/h3>");
document.write("                        <div class=\"control control--checkbox\">");
document.write("                            <input class=\"control-checkbox\" type=\"checkbox\" id=\"ckbGeonamesLayer\">");
document.write("                            <label for=\"ckbGeonamesLayer\">Afficher la couche<\/label>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("");
document.write("                    <div class=\"panel-content\">");
document.write("                        <h3 class=\"panel-titleSecondary\">Casqy<\/h3>");
document.write("                        <div class=\"control control--checkbox\">");
document.write("                            <input class=\"control-checkbox\" type=\"checkbox\" id=\"ckbCasqyPoints\">");
document.write("                            <label for=\"ckbCasqyPoints\">Points<\/label>");
document.write("                            <input class=\"control-checkbox\" type=\"checkbox\" id=\"ckbCasqyLines\">");
document.write("                            <label for=\"ckbCasqyLines\">Lines<\/label>");
document.write("                            <input class=\"control-checkbox\" type=\"checkbox\" id=\"ckbCasqyGeoPortail\">");
document.write("                            <label for=\"ckbCasqyGeoPortail\">Geoportail<\/label>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("            <\/div>");
document.write("            <div class=\"panel panel--expandable\">");
document.write("                <h2 class=\"panel-titlePrimary icon icon--tools\">Outils<\/h2>");
document.write("                <div class=\"panel-inner\">");
document.write("                    <div class=\"panel-content\">");
document.write("                        <h3 class=\"panel-titleSecondary\">Mesure<\/h3>");
document.write("                        <div class=\"control control--buttonGroup\">");
document.write("                            <div class=\"control--buttonGroup-item\">");
document.write("                                <button class=\"control-button-activable\" id=\"btnPoint\">Point<\/button>");
document.write("                            <\/div>");
document.write("                            <div class=\"control--buttonGroup-item\">");
document.write("                                <button class=\"control-button-activable\" id=\"btnLine\">Line<\/button>");
document.write("                            <\/div>");
document.write("                            <div class=\"control--buttonGroup-item\">");
document.write("                                <button class=\"control-button-activable\" id=\"btnVolume\">Volume<\/button>");
document.write("                            <\/div>");
document.write("");
document.write("                            <!--");
document.write("                            <div class=\"control--buttonGroup-item\">");
document.write("                                <button class=\"control-button-activable\" id=\"btnClean\">Clear All<\/button>");
document.write("                            <\/div>");
document.write("                            <div class=\"control--buttonGroup-item\">");
document.write("                                <button class=\"control-button-activable\" id=\"btnSave\">Save As<\/button>");
document.write("                            <\/div>  -->");
document.write("                        <\/div>");
document.write("");
document.write("                         <div class=\"control \">");
document.write("                                <button class=\"control-button\" id=\"btnClean\">Clear<\/button>");
document.write("                                <button class=\"control-button\" id=\"btnSave\">kml<\/button>");
document.write("                                <button class=\"control-button\" id=\"btnSaveSHP\">shp<\/button>");
document.write("                                <button class=\"control-button\" id=\"btnExportClassification\">Export Classif<\/button>");
document.write("                         <\/div>");
document.write("                        <div>");
document.write("                            <label for=\"choice_class\">Classe:<\/label>");
document.write("                            <input type=\"text\" id=\"choice_class\" list=\"classID\" >");
document.write("                            <datalist id =\"classID\">");
document.write("                                Pas compatible HTML5");
document.write("                            <\/datalist>");
document.write("                             <input class=\"control-checkbox\" type=\"checkbox\" id=\"chbxFilterSurface\">");
document.write("                                <label for=\"chbxFilterSurface\"> F <\/label>");
document.write("                        <\/div>");
document.write("                         <div class=\"control control--radio\">");
document.write("                                    <input class=\"control-checkbox\" type=\"checkbox\" id=\"chbxSnappON\">");
document.write("                                    <label for=\"chbxSnappON\"> Snapping <\/label>");
document.write("                                    <input class=\"control-checkbox\" type=\"checkbox\" id=\"chbxComputeNormal\">");
document.write("                                    <label for=\"chbxComputeNormal\"> Sidewalk<\/label>");
document.write("                                    <input class=\"control-checkbox\" type=\"checkbox\" id=\"chbxZebra\">");
document.write("                                    <label for=\"chbxZebra\"> Attach Zebra<\/label>");
document.write("                         <\/div>");
document.write("                    <\/div>");
document.write("                    <!-- Exemple de boutons radios -->");
document.write("                    <!--                    <div class=\"panel-content\">");
document.write("                                            <h3 class=\"panel-titleSecondary\">Un dernier choix<\/h3>");
document.write("                                            <div class=\"control control--radio\">");
document.write("                                                <input class=\"control-radio\" type=\"radio\" name=\"ouinon\" id=\"radio1\">");
document.write("                                                <label for=\"radio1\">Cette option<\/label>");
document.write("                                            <\/div>");
document.write("                                            <div class=\"control control--radio\">");
document.write("                                                <input class=\"control-radio\" type=\"radio\" name=\"ouinon\" id=\"radio2\">");
document.write("                                                <label for=\"radio2\">Ou celle-là<\/label>");
document.write("                                            <\/div>");
document.write("                                    <\/div>-->");
document.write("                <\/div>");
document.write("");
document.write("            <\/div>");
document.write("             <div class=\"panel panel--expandable\" id=\"biomasse\" style=\"display:none\">");
document.write("                <h2 class=\"panel-titlePrimary icon icon--buildings\">Mesure Biomasse<\/h2>");
document.write("                <div class=\"panel-inner\">");
document.write("                    <div class=\"panel-content\">");
document.write("                       <div class=\"control control--radio\">");
document.write("                                    <input class=\"control-checkbox\" type=\"checkbox\" id=\"chbxSnappON\">");
document.write("                                    <label for=\"chbxSnappON\"> Burn the trees <\/label>");
document.write("                                    <input class=\"control-checkbox\" type=\"checkbox\" id=\"chbxComputeNormal\">");
document.write("                                    <label for=\"chbxComputeNormal\"> Flood everything<\/label>");
document.write("                         <\/div>");
document.write("                    <\/div>");
document.write("");
document.write("                <\/div>");
document.write("            <\/div>");
document.write("             <div class=\"panel panel--expandable\" id=\"PMR\" style=\"display:block\">");
document.write("                <h2 class=\"panel-titlePrimary icon icon--pmr\">Diagnostic PMR<\/h2>");
document.write("                <div class=\"panel-inner  \">");
document.write("                    <div class=\"panel-content \">");
document.write("                        <div class=\"control  \">");
document.write("                                <input class=\"control-checkbox\" type=\"checkbox\" id=\"checkboxAnnotations\">");
document.write("                                <label for=\"checkboxAnnotations\">Annotations<\/label>");
document.write("                                <button class=\"control-button\" id=\"btnPrevious\" ><<\/button>");
document.write("                                <button class=\"control-button\" id=\"btnNext\">><\/button>");
document.write("                         <\/div>");
document.write("                    <\/div>");
document.write("");
document.write("                <\/div>");
document.write("            <\/div>");
document.write("              <div class=\"panel panel--expandable\" id=\"geovelo\" style=\"display:block\">");
document.write("                <h2 class=\"panel-titlePrimary icon icon--bicycle\">Geovelo<\/h2>");
document.write("                <div class=\"panel-inner \">");
document.write("                    <div class=\"panel-content \">");
document.write("                        <div class=\"control  \">");
document.write("                       	<!--");
document.write("                                <input class=\"control-checkbox\" type=\"checkbox\" id=\"checkboxGeoveloPOI\">");
document.write("                                <label for=\"checkboxGeoveloPOI\">Saisie POI<\/label>");
document.write("                                <button class=\"control-button\" id=\"btnPreviousGeo\" ><<\/button>");
document.write("                                <button class=\"control-button\" id=\"btnNextGeo\">><\/button>");
document.write("                                <button class=\"control-button\" id=\"btnGenerateItinerary\" >Générer itinéraire<\/button>");
document.write("");
document.write("						-->");
document.write("<!-- old geovelo menu");
document.write("");
document.write("                                	<section id=\"intiControl\">");
document.write("		                                <input class=\"control-checkbox\" type=\"checkbox\" id=\"checkboxEditDroppedObject\">");
document.write("		                                <label for=\"checkboxEditDroppedObject\">Edit Dropped Object<\/label> <br \/>");
document.write("                                		<button class=\"control-button\" id=\"btnLoadItinerary\">Load itinerary<\/button>");
document.write("                                		<select id=\"listIti\"><\/select> <br \/>");
document.write("                                		<button class=\"control-button\" id=\"btnCreateItinerary\">Create new itinerary<\/button>");
document.write("                                		<button class=\"control-button\" id=\"btnSaveItinerary\" >Save itinerary<\/button>");
document.write("                                		<input id=\"iti_name\" type=\"text\" placeholder=\"Name of itineray\"> <br \/>");
document.write("                                		<textarea id=\"iti_descp\" rows=\"3\" cols=\"30\" placeholder=\"Description...\" \/><\/textarea> <br \/>");
document.write("");
document.write("	                                <\/section>");
document.write("	                                <section id=\"viewPointSection\">");
document.write("		                                	<button class=\"control-button\" id=\"btnAddViewPoint\">Add view point<\/button>");
document.write("		                                	<button class=\"control-button\" id=\"captureView\">Capture view<\/button>");
document.write("		                                	<button class=\"control-button\" id=\"btnSaveViewPoint\" >Save view point<\/button>");
document.write("		                                <div id=\"viewPointControl\">");
document.write("	                                		<button class=\"control-button\" id=\"viewPointPrevious\" data-increment=\"-1\">Previous<\/button>");
document.write("	                               	 		<button class=\"control-button\" id=\"viewPointNext\" data-increment=\"1\">Next<\/button>");
document.write("	                         			<\/div>");
document.write("                         			<\/section>");
document.write("");
document.write("-->");
document.write("");
document.write("								<div id=\"itinerary\">");
document.write("");
document.write("									<div id=\"ABsearch\">");
document.write("										<div id=\"A\">");
document.write("										<strong>A<\/strong> <input id=\"searchA\">");
document.write("										<\/div>");
document.write("										<input class=\"control-button\" id=\"searchAB\" type=\"submit\" value=\"Aller\">");
document.write("										<div id=\"B\">");
document.write("										<strong>B<\/strong> <input id=\"searchB\">");
document.write("										<\/div>");
document.write("									<\/div>");
document.write("");
document.write("									<hr>");
document.write("");
document.write("									<div id=\"loadIti\">");
document.write("										<div class=\"left\">");
document.write("											<select id=\"listIti\"><\/select> <br>");
document.write("											<button class=\"control-button\" id=\"viewIti\">>||<\/button>");
document.write("											<button class=\"control-button\" id=\"viewPointPrevious\" data-increment=\"-1\"><<<\/button>");
document.write("			                               	<button class=\"control-button\" id=\"viewPointNext\" data-increment=\"1\">>><\/button>");
document.write("			                            <\/div>");
document.write("			                            <div class=\"right\">");
document.write("		                               		<img id=\"itiPreview\" height=\"58\" width=\"93\" alt=\"preview\">");
document.write("		                               	<\/div>");
document.write("	                               	<\/div>");
document.write("");
document.write("	                               	<div id=\"newIti\">");
document.write("		                               	<br>");
document.write("		                               	<br>");
document.write("	                               		<h4 style=\"margin-bottom: 5px;\">Créer nouvelle balade<\/h4>");
document.write("	                               		<div class=\"left\">");
document.write("	                               			<input id=\"iti_name\" type=\"text\" placeholder=\"Name of itineray\"> <br \/>");
document.write("	                                		<textarea id=\"iti_descp\" rows=\"3\" cols=\"25\" placeholder=\"Description...\" \/><\/textarea> <br \/>");
document.write("	                                	<\/div>");
document.write("	                                	<div class=\"right\">");
document.write("	                                		<button class=\"control-button\" id=\"btnCreateItinerary\">Créer<\/button>");
document.write("	                               			<button class=\"control-button\" id=\"btnSaveItinerary\" >Sauver<\/button>");
document.write("	                               		<\/div>");
document.write("	                               	<\/div>");
document.write("");
document.write("								<\/div>");
document.write("								<!-- end of itinerary section -->");
document.write("");
document.write("");
document.write("                         <\/div>");
document.write("                    <\/div>");
document.write("");
document.write("                <\/div>");
document.write("            <\/div>");
document.write("            <div class=\"panel panel--expandable\">");
document.write("                <h2 class=\"panel-titlePrimary icon icon--buildings\">Modèles 3D<\/h2>");
document.write("                <div class=\"panel-inner\">");
document.write("                    <div class=\"panel-content\">");
document.write("                        <div class=\"control \">");
document.write("                            <div class=\"models-info\">");
document.write("                                <ul class=\"model-list\">");
document.write("                                    <li class=\"empty-list\">Aucun modèle chargé<\/li>");
document.write("                                <\/ul>");
document.write("                            <\/div>");
document.write("                            <button class=\"control-button\" id=\"btImportModel\">Importer<\/button>");
document.write("                            <input type=\"file\" id=\"inputModel\" style=\"display:none\" \/>");
document.write("                            <button class=\"control-button\" id=\"btSaveModel\">Sauvegarder<\/button>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("                    <div class=\"panel-content\">");
document.write("                        <h3 class=\"panel-titleSecondary\">Manipulation<\/h3>");
document.write("                        <div class=\"control control--buttonGroup\">");
document.write("                            <div class=\"control--buttonGroup-item\">");
document.write("                                <button class=\"control-button-activable\" id=\"btTranslate\" disabled=\"true\">T<\/button>");
document.write("                            <\/div>");
document.write("                            <div class=\"control--buttonGroup-item\">");
document.write("                                <button class=\"control-button-activable\" id=\"btRotate\" disabled=\"true\">R<\/button>");
document.write("                            <\/div>");
document.write("                            <div class=\"control--buttonGroup-item\">");
document.write("                                <button class=\"control-button-activable\" id=\"btScale\" disabled=\"true\">S<\/button>");
document.write("                            <\/div>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("            <\/div>");
document.write("            <div class=\"panel panel--expandable\">");
document.write("                <h2 class=\"panel-titlePrimary icon icon--settings\">Réglages<\/h2>");
document.write("                <div class=\"panel-inner\">");
document.write("");
document.write("                            <h3 class=\"panel-titleSecondary\">Effets<\/h3>");
document.write("                            <div class=\"panel-content\">");
document.write("                                <div class=\"control control--checkbox\">");
document.write("                                    <input class=\"control-checkbox\" type=\"checkbox\" checked id=\"checkboxEffects\">");
document.write("                                    <label for=\"checkboxEffects\">Activer effets <\/label>");
document.write("                                <\/div>");
document.write("                            <\/div>");
document.write("                             <div class=\"panel-content\">");
document.write("                                <div class=\"control control--checkbox\">");
document.write("                                <input class=\"control-checkbox\" type=\"checkbox\" id=\"checkboxClimate\">");
document.write("                                   <label for=\"checkboxClimate\">Activer climat<\/label>");
document.write("                                <\/div>");
document.write("                               <div class=\"control control--range\">");
document.write("                                   <label class=\"panel-titleSecondary\">Variation<\/label>");
document.write("                                   <div class=\"control-range\" data-min=\"1\" data-max=\"100\" data-value=\"90\" id=\"rangeClimate\"><\/div>");
document.write("                               <\/div>");
document.write("");
document.write("                               <div class=\"control control--checkbox\">");
document.write("                                   <input class=\"control-checkbox\" type=\"checkbox\" id=\"checkboxSharpen\">");
document.write("                                   <label for=\"checkboxSharpen\">Netteté<\/label>");
document.write("                                   <input class=\"control-checkbox\" type=\"checkbox\" id=\"checkboxToneMapping\">");
document.write("                                   <label for=\"checkboxToneMapping\">Tone Mapping<\/label>");
document.write("                               <\/div>");
document.write("");
document.write("                               <div class=\"control control--range\">");
document.write("                                   <label class=\"panel-titleSecondary\">Saturation<\/label>");
document.write("                                   <div class=\"control-range\" data-min=\"0\" data-max=\"200\" data-value=\"100\" id=\"rangeSaturation\"><\/div>");
document.write("                               <\/div>");
document.write("                               <div class=\"control control--range\">");
document.write("                                   <label class=\"panel-titleSecondary\">Teinte<\/label>");
document.write("                                   <div class=\"control-range\" data-min=\"0\" data-max=\"200\" data-value=\"100\" id=\"rangeHue\"><\/div>");
document.write("                               <\/div>");
document.write("                               <div class=\"control control--range\">");
document.write("                                   <label class=\"panel-titleSecondary\">Contraste<\/label>");
document.write("                                   <div class=\"control-range\" data-min=\"0\" data-max=\"200\" data-value=\"100\" id=\"rangeContrast\"><\/div>");
document.write("                               <\/div>");
document.write("                               <div class=\"control control--range\">");
document.write("                                   <label class=\"panel-titleSecondary\">Luminance<\/label>");
document.write("                                   <div class=\"control-range\" data-min=\"0\" data-max=\"200\" data-value=\"100\" id=\"rangeBrightness\"><\/div>");
document.write("                               <\/div>");
document.write("");
document.write("                                <div class=\"control control--checkbox\">");
document.write("                                   <input class=\"control-checkbox\" type=\"checkbox\" id=\"checkbox3DGlasses\">");
document.write("                                   <label for=\"checkbox3DGlasses\">3D Glasses<\/label>");
document.write("                                   <button class=\"control-button\" id=\"switch3DGlasses\">switch rendering<\/button>");
document.write("                               <\/div>");
document.write("                                 <div class=\"control control--range\">");
document.write("                                   <label class=\"panel-titleSecondary\">Base<\/label>");
document.write("                                   <div class=\"control-range\" data-min=\"0\" data-max=\"300\" data-value=\"200\" id=\"rangeBase3D\"><\/div>");
document.write("                               <\/div>");
document.write("                             <\/div>");
document.write("               <\/div>");
document.write("            <\/div>");
document.write("            <div class=\"panel panel--expandable\">");
document.write("                <h2 class=\"panel-titlePrimary icon icon--user\">Compte<\/h2>");
document.write("                <div class=\"panel-inner\">");
document.write("                    <div class=\"panel-content account\">");
document.write("                        <?php if (!empty($_SESSION[\"user_id\"])) { ?>");
document.write("                            <form action=\"php\/manageConnection.php\" method=\"POST\" id=\"deconnect\">");
document.write("                                <p class=\"user-info\">Utilisateur <strong><?php echo $_SESSION[\"login\"]; ?><\/strong> connecté<\/p>");
document.write("                                <input type=\"hidden\" name=\"deconnect\" value=\"yes\" id=\"connected\"\/>");
document.write("                                <input class=\"control-button\" type=\"submit\" value=\"Déconnexion\"\/>");
document.write("                            <\/form>");
document.write("                        <?php } else { ?>");
document.write("                            <div class=\"control connexion\">");
document.write("                                <form action=\"php\/manageConnection.php\" method=\"POST\" id=\"connect\">");
document.write("                                    <label for=\"login\">Login<\/label>");
document.write("                                    <input class=\"control-text\" name=\"login\" type=\"text\" placeholder=\"Login\" \/>");
document.write("                                    <label for=\"pass\">Mot de passe<\/label>");
document.write("                                    <input class=\"control-text\" name=\"pass\" type=\"password\" placeholder=\"Mot de passe\" \/>");
document.write("                                    <input class=\"control-button\" type=\"submit\" value=\"Connexion\" \/>");
document.write("                                <\/form>");
document.write("                            <\/div>");
document.write("                        <?php } ?>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("            <\/div>");
document.write("");
document.write("        <\/div>");
document.write("        <div class=\"localisation\" id=\"localisation\">");
document.write("            <p class=\"localisation-text\"><\/p>");
document.write("        <\/div>");
document.write("");
document.write("        <div class=\"viewport\" oncontextmenu=\"return false\" id=\"container\" tabindex=\"-1\">");
document.write("            <div id=\"dynamicInput\"><\/div>");
document.write("        <\/div>");
document.write("");
document.write("<!-- ");
document.write("        <div style=\" position:absolute;  right: 0px; bottom:-5px;  z-index: 5;\" id=\"sponsors\" >");
document.write("");
document.write("          <img src=\"images\/sponsors\/LOGO-IDF-SIGNATURE-CAMPAGNE-01.jpg\"  height=\"75\" alt=\"towns+ - Site officiel\" id=\"logosp1\">");
document.write("          <img src=\"images\/sponsors\/LOGO_FUTUR_EN_SEINE_FR.JPG\"  height=\"75\"  alt=\"towns+ - Site officiel\" id=\"logosp2\">");
document.write("          <img src=\"images\/sponsors\/logo_Cap_Digital_JPG_HD_RVB.JPG\"   height=\"75\"  alt=\"towns+ - Site officiel\" id=\"logosp3\">");
document.write("          <img src=\"images\/geovelo-big.png\"  height=\"70\" alt=\"towns+ - Site officiel\" id=\"logogeoveloe\">");
document.write("          <img src=\"images\/logo_ign.jpg\"  height=\"145\" alt=\"towns+ - Site officiel\" id=\"logoIGN\">");
document.write("        <\/div>");
document.write("-->");
document.write(" 	");
document.write("        <div style=\"background-color: #2c3e50; position:absolute;  right: 900px; bottom:-5px;  z-index: 5;\" id=\"up\" >");
document.write("            <button type=\"button\"><img src=\"images\/up.png\"  height=\"20\" id=\"upButton\">  <\/button>");
document.write("          <!--  <button type=\"button\"  style=\"background-color:#2c3e50;\"><img src=\"images\/up.png\"  height=\"20\" id=\"upButton\">  <\/button>   -->");
document.write("        <!--  <img align=\"middle\" src=\"images\/up.png\"  height=\"90\" alt=\"towns+ - Site officiel\" id=\"upButton\">  -->");
document.write("        <\/div>");
document.write("");
document.write("        <div style=\"position:absolute;  right: 0px; bottom:0px;  z-index: 5;\" >");
document.write("            <button type=\"button\" id=\"reportButton\" style=\"height:14px; background-color: rgba(1, 1, 1, 0.5);  color: white; border: 0; border-radius: 0px; font-size: 11px;\">report <\/button>");
document.write("        <\/div>");
document.write("");
document.write("");
document.write("        <!-- Alex Stuff test -->");
document.write("        <div style=\"background-color: black; height:0px; width:100%; position:absolute; top:0px;\" id=\"b1\"><\/div>");
document.write("        <div style=\"background-color: black; height:0px; width:100%; position:absolute; bottom:0px;\" id=\"b2\"><\/div>");
document.write("");
document.write("");
document.write("");
document.write("    <\/body>");
document.write("<\/html>");
